early_stopping:
  _target_: pytorch_lightning.callbacks.early_stopping.EarlyStopping
  monitor: val_loss
  patience: 3
  verbose: false
  mode: min

model_checkpoint:
  _target_: pytorch_lightning.callbacks.model_checkpoint.ModelCheckpoint
  monitor: val_loss
  dirpath: model/
  filename: "model-{epoch:02d}-{val_loss:.2f}"
  save_top_k: -1
  mode: min